// Generated by CoffeeScript 1.11.1
var activate, chalk, inquirer, jsonfile;

chalk = require('chalk');

jsonfile = require('jsonfile');

inquirer = require('inquirer');

activate = function(file_name, clbFunction) {
  return jsonfile.readFile(file_name, function(err, obj) {
    var choices, k, v;
    if (err) {
      clbFunction(false);
      return;
    }
    choices = [];
    for (k in obj) {
      v = obj[k];
      choices.push({
        name: k
      });
    }
    return inquirer.prompt({
      type: 'checkbox',
      message: 'Select Profile',
      name: 'profile',
      choices: choices
    }).then(function(answers) {
      var i, j, len, profile_var, ref;
      ref = answers.profile;
      for (j = 0, len = ref.length; j < len; j++) {
        i = ref[j];
        profile_var = obj[i];
        for (k in profile_var) {
          v = profile_var[k];
          process.env[k] = v;
        }
      }
      return clbFunction(true);
    });
  });
};

module.exports = activate;
